---
- hosts: all
  become: yes

  tasks:
    - name: docker-compose.yml file copy
      copy:
        src: beta_agent_docker_compose.yml
        dest: /var/docker-compose.yml
        owner: root
        group: root
        mode: '0644'

    - name: docker login
      shell: docker login beta-watcher-registry.kr.ncr.ntruss.com -u 04653D30386ABB3D3E21 -p 4C71DA00C492402EE8EE33CA39E46F9E9ACD3C65

    - name: prune everything
      shell: docker system prune --volumes -a -f

    - name: docker-compose up
      shell: docker-compose up -d
      args:
        chdir: /var