version: "3"
 
services:
  agent:
    container_name: agent
    environment:
        - HOST_HOSTNAME=${HOSTNAME}
    hostname: "${HOST_HOSTNAME}"
    image: beta-watcher-registry.kr.ncr.ntruss.com/agent:latest
    volumes:
      - /var/watcher-v2/log:/var/watcher-v2/log
      - /var/watcher-v2/data:/var/watcher-v2/data
    working_dir: /opt/watcher-v2-agent/
    command: python3 main.py

  httpd:
    container_name: httpd
    image: beta-watcher-registry.kr.ncr.ntruss.com/httpd:latest
    working_dir: /etc/httpd
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      - agent

  filebeat:
    container_name: filebeat
    image: beta-watcher-registry.kr.ncr.ntruss.com/filebeat:latest
    volumes:
      - /var/watcher-v2/log:/var/watcher-v2/log
    working_dir: /usr/share/filebeat
    command: filebeat run
    depends_on:
      - agent