---
- hosts: all

  tasks:
    - name: add docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      become: yes

    - name: install docker-ce-3:20.10.8-3.el7.x86_64
      package:
        name: docker-ce-3:20.10.8-3.el7.x86_64
        state: present
      become: yes

    - name: install git
      package:
        name: git-1.8.3.1-23.el7_8
        state: present
      become: yes

    - name: install containerd.io
      package:
        name: containerd.io-1.5.11-3.1.el7.x86_64
        state: present
      become: yes

    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
      become: yes